# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('loc', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Zurich', 'Zurich'), ('Paris', 'Paris'), ('Munich', 'Munich'), ('Tokyo', 'Tokyo'), ('London', 'London'), ('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Berlin', 'Berlin')], max_length=65)),
                ('occupants', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=65)),
                ('hood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.Neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('prof_pic', models.ImageField(blank=True, default='profile/a.jpg', upload_to='profiles/')),
                ('bio', models.CharField(default='Welcome Me!', max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoodwatch.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
