# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.FileField(default=1, upload_to='posts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='loc',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Eldoret', 'Eldoret'), ('Naivasha', 'Naivasha'), ('Kakamega', 'Kakamega'), ('Kakamega', 'Kakamega'), ('Kisii', 'Kisii'), ('Mandera', 'Mandera')], max_length=65),
        ),
    ]
