# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Technology',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sitename',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
