# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('loc', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Zurich', 'Zurich'), ('Paris', 'Paris'), ('Munich', 'Munich'), ('Tokyo', 'Tokyo'), ('London', 'London'), ('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Berlin', 'Berlin')], max_length=65)),
                ('occupants', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
    ]
