# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0002_auto_20181022_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.FileField(upload_to='hoods/'),
        ),
    ]
